/* Generated By:JavaCC: Do not edit this line. compiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPARITMETICO = 6;
  /** RegularExpression Id. */
  int OPRELACIONAL = 7;
  /** RegularExpression Id. */
  int OPLOGICO = 8;
  /** RegularExpression Id. */
  int ASIGNACION = 9;
  /** RegularExpression Id. */
  int OPASIGNACION = 10;
  /** RegularExpression Id. */
  int INCREMENTO = 11;
  /** RegularExpression Id. */
  int DECREMENTO = 12;
  /** RegularExpression Id. */
  int COMPBITS = 13;
  /** RegularExpression Id. */
  int OPTERNARIO = 14;
  /** RegularExpression Id. */
  int APUNTADOR = 15;
  /** RegularExpression Id. */
  int OPFUSIONNULA = 16;
  /** RegularExpression Id. */
  int LAMBDA = 17;
  /** RegularExpression Id. */
  int PARIZQ = 18;
  /** RegularExpression Id. */
  int PARDER = 19;
  /** RegularExpression Id. */
  int LLAVEIZQ = 20;
  /** RegularExpression Id. */
  int LLAVEDER = 21;
  /** RegularExpression Id. */
  int CORIZQ = 22;
  /** RegularExpression Id. */
  int CORDER = 23;
  /** RegularExpression Id. */
  int PUNTO = 24;
  /** RegularExpression Id. */
  int COMA = 25;
  /** RegularExpression Id. */
  int COMILLAS = 26;
  /** RegularExpression Id. */
  int DOSPUNTOS = 27;
  /** RegularExpression Id. */
  int FINLINEA = 28;
  /** RegularExpression Id. */
  int INICIOCOMENTARIO = 29;
  /** RegularExpression Id. */
  int FINCOMENTARIO = 30;
  /** RegularExpression Id. */
  int IF = 31;
  /** RegularExpression Id. */
  int SINO = 32;
  /** RegularExpression Id. */
  int ELSIF = 33;
  /** RegularExpression Id. */
  int SWITCH = 34;
  /** RegularExpression Id. */
  int CASE = 35;
  /** RegularExpression Id. */
  int FINCASE = 36;
  /** RegularExpression Id. */
  int MIENTRAS = 37;
  /** RegularExpression Id. */
  int FOR = 38;
  /** RegularExpression Id. */
  int FOREACH = 39;
  /** RegularExpression Id. */
  int REPETIR = 40;
  /** RegularExpression Id. */
  int HASTA = 41;
  /** RegularExpression Id. */
  int NUMERO = 42;
  /** RegularExpression Id. */
  int CONSTANTE = 43;
  /** RegularExpression Id. */
  int TIPODATO = 44;
  /** RegularExpression Id. */
  int NULO = 45;
  /** RegularExpression Id. */
  int VALOR_BOOLEANO = 46;
  /** RegularExpression Id. */
  int FUNCION = 47;
  /** RegularExpression Id. */
  int CLASE = 48;
  /** RegularExpression Id. */
  int VALOR_OBJETO = 49;
  /** RegularExpression Id. */
  int TIPO_INTERFAZ = 50;
  /** RegularExpression Id. */
  int NEXT = 51;
  /** RegularExpression Id. */
  int TIPO_DELEGADO = 52;
  /** RegularExpression Id. */
  int COMO = 53;
  /** RegularExpression Id. */
  int GLOBAL = 54;
  /** RegularExpression Id. */
  int EN = 55;
  /** RegularExpression Id. */
  int RETORNO = 56;
  /** RegularExpression Id. */
  int THEN = 57;
  /** RegularExpression Id. */
  int ARREGLO = 58;
  /** RegularExpression Id. */
  int ITERACION = 59;
  /** RegularExpression Id. */
  int PRUEBA = 60;
  /** RegularExpression Id. */
  int ATRAPADOR = 61;
  /** RegularExpression Id. */
  int COMPARADOR = 62;
  /** RegularExpression Id. */
  int HILO = 63;
  /** RegularExpression Id. */
  int ARCHIVO = 64;
  /** RegularExpression Id. */
  int ABRIR_ARCHIVO = 65;
  /** RegularExpression Id. */
  int LEER_ARCHIVO = 66;
  /** RegularExpression Id. */
  int LEER_LINEA = 67;
  /** RegularExpression Id. */
  int ESCRIBIR = 68;
  /** RegularExpression Id. */
  int IMPRIMIR = 69;
  /** RegularExpression Id. */
  int EJECUCION = 70;
  /** RegularExpression Id. */
  int ERROR_EXCEPCION = 71;
  /** RegularExpression Id. */
  int ERROR_BLOQUEO = 72;
  /** RegularExpression Id. */
  int ERROR_FINALIZACION = 73;
  /** RegularExpression Id. */
  int SELECTOR = 74;
  /** RegularExpression Id. */
  int METODO_DESDE = 75;
  /** RegularExpression Id. */
  int METODO_TIPO = 76;
  /** RegularExpression Id. */
  int VALOR_DEFAULT = 77;
  /** RegularExpression Id. */
  int NUEVO = 78;
  /** RegularExpression Id. */
  int BIBLIOTECA = 79;
  /** RegularExpression Id. */
  int IMPORTAR_BIBLIOTECA = 80;
  /** RegularExpression Id. */
  int ABSTRACCION = 81;
  /** RegularExpression Id. */
  int GET = 82;
  /** RegularExpression Id. */
  int SET = 83;
  /** RegularExpression Id. */
  int THROW = 84;
  /** RegularExpression Id. */
  int PUNTERO = 85;
  /** RegularExpression Id. */
  int MOD_ABSTRAC = 86;
  /** RegularExpression Id. */
  int SUPER = 87;
  /** RegularExpression Id. */
  int PARAMETROS = 88;
  /** RegularExpression Id. */
  int TIPO_METODO = 89;
  /** RegularExpression Id. */
  int ESTATICO = 90;
  /** RegularExpression Id. */
  int VALOR = 91;
  /** RegularExpression Id. */
  int INPUT = 92;
  /** RegularExpression Id. */
  int FINFOR = 93;
  /** RegularExpression Id. */
  int EVENTO = 94;
  /** RegularExpression Id. */
  int REFERENCIA = 95;
  /** RegularExpression Id. */
  int COMPROBAR = 96;
  /** RegularExpression Id. */
  int DESCOMPROBAR = 97;
  /** RegularExpression Id. */
  int SINCRONIZAR = 98;
  /** RegularExpression Id. */
  int CORRER = 99;
  /** RegularExpression Id. */
  int IGNORAR = 100;
  /** RegularExpression Id. */
  int INSTRUCHILO = 101;
  /** RegularExpression Id. */
  int REMOVE = 102;
  /** RegularExpression Id. */
  int CLEAR = 103;
  /** RegularExpression Id. */
  int REVERSE = 104;
  /** RegularExpression Id. */
  int COPIAR = 105;
  /** RegularExpression Id. */
  int MAXIMO = 106;
  /** RegularExpression Id. */
  int MINIMO = 107;
  /** RegularExpression Id. */
  int SUMAR = 108;
  /** RegularExpression Id. */
  int FINCLASE = 109;
  /** RegularExpression Id. */
  int FINSI = 110;
  /** RegularExpression Id. */
  int FINMETODO = 111;
  /** RegularExpression Id. */
  int ADJUNTAR = 112;
  /** RegularExpression Id. */
  int EXTENDER = 113;
  /** RegularExpression Id. */
  int INSERTAR = 114;
  /** RegularExpression Id. */
  int MODMATH = 115;
  /** RegularExpression Id. */
  int HEIGHT = 116;
  /** RegularExpression Id. */
  int WIDTH = 117;
  /** RegularExpression Id. */
  int LEFT = 118;
  /** RegularExpression Id. */
  int RIGHT = 119;
  /** RegularExpression Id. */
  int TOP = 120;
  /** RegularExpression Id. */
  int INDICE = 121;
  /** RegularExpression Id. */
  int METODO = 122;
  /** RegularExpression Id. */
  int TAG = 123;
  /** RegularExpression Id. */
  int BOTTOM = 124;
  /** RegularExpression Id. */
  int INSTANCIA = 125;
  /** RegularExpression Id. */
  int CONTAR = 126;
  /** RegularExpression Id. */
  int ORDENAR = 127;
  /** RegularExpression Id. */
  int TIEMPO = 128;
  /** RegularExpression Id. */
  int ALEATORIO = 129;
  /** RegularExpression Id. */
  int CLOSE = 130;
  /** RegularExpression Id. */
  int BUSCAR = 131;
  /** RegularExpression Id. */
  int RENOMBRAR = 132;
  /** RegularExpression Id. */
  int FUNCMAT = 133;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 134;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<OPARITMETICO>",
    "<OPRELACIONAL>",
    "<OPLOGICO>",
    "\"=\"",
    "<OPASIGNACION>",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"?:\"",
    "<APUNTADOR>",
    "\"??\"",
    "\"lambda\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "<COMILLAS>",
    "\":\"",
    "\";\"",
    "\"#<\"",
    "\">#\"",
    "\"if\"",
    "\"else\"",
    "\"elsif\"",
    "\"switch\"",
    "\"case\"",
    "\"endcase\"",
    "\"while\"",
    "\"for\"",
    "\"foreach\"",
    "\"rept\"",
    "\"until\"",
    "<NUMERO>",
    "\"cons\"",
    "<TIPODATO>",
    "\"null\"",
    "<VALOR_BOOLEANO>",
    "\"func\"",
    "\"class\"",
    "\"object\"",
    "\"interface\"",
    "\"next\"",
    "\"del\"",
    "\"as\"",
    "\"global\"",
    "\"in\"",
    "\"return\"",
    "\"then\"",
    "\"array\"",
    "\"continue\"",
    "\"try\"",
    "\"oops\"",
    "\"like\"",
    "\"strand\"",
    "\"File\"",
    "\"open\"",
    "\"readfile\"",
    "<LEER_LINEA>",
    "<ESCRIBIR>",
    "\"display\"",
    "\"exec\"",
    "\"excep\"",
    "\"raise\"",
    "\"finally\"",
    "\"select\"",
    "\"from\"",
    "\"type\"",
    "\"default\"",
    "\"new\"",
    "\"packg\"",
    "\"import\"",
    "\"abstract\"",
    "\"get\"",
    "\"set\"",
    "\"throw\"",
    "\"this\"",
    "\"override\"",
    "\"super\"",
    "\"params\"",
    "<TIPO_METODO>",
    "\"static\"",
    "\"value\"",
    "\"input\"",
    "\"endfor\"",
    "\"event\"",
    "\"ref\"",
    "\"checked\"",
    "\"unchecked\"",
    "\"sync\"",
    "\"run\"",
    "\"pass\"",
    "<INSTRUCHILO>",
    "\"Remove\"",
    "\"Clear\"",
    "\"Reverse\"",
    "\"Copy\"",
    "\"Max\"",
    "\"Min\"",
    "\"Sum\"",
    "\"classend\"",
    "\"endif\"",
    "\"last\"",
    "\"append\"",
    "\"extend\"",
    "\"insert\"",
    "\"Math\"",
    "\"Height\"",
    "\"Width\"",
    "\"Left\"",
    "\"Right\"",
    "\"Top\"",
    "\"Index\"",
    "\"void\"",
    "\"Tag\"",
    "\"Bottom\"",
    "\"instance\"",
    "\"count\"",
    "\"sort\"",
    "\"time\"",
    "\"random\"",
    "\"close\"",
    "\"seek\"",
    "\"rename\"",
    "<FUNCMAT>",
    "<IDENTIFICADOR>",
  };

}
