/* Generated By:JavaCC: Do not edit this line. compiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPARITMETICO = 6;
  /** RegularExpression Id. */
  int OPRELACIONAL = 7;
  /** RegularExpression Id. */
  int OPLOGICO = 8;
  /** RegularExpression Id. */
  int ASIGNACION = 9;
  /** RegularExpression Id. */
  int OPASIGNACION = 10;
  /** RegularExpression Id. */
  int INCREMENTO = 11;
  /** RegularExpression Id. */
  int DECREMENTO = 12;
  /** RegularExpression Id. */
  int COMPBITS = 13;
  /** RegularExpression Id. */
  int OPTERNARIO = 14;
  /** RegularExpression Id. */
  int APUNTADOR = 15;
  /** RegularExpression Id. */
  int OPFUSIONNULA = 16;
  /** RegularExpression Id. */
  int LAMBDA = 17;
  /** RegularExpression Id. */
  int PARIZQ = 18;
  /** RegularExpression Id. */
  int PARDER = 19;
  /** RegularExpression Id. */
  int LLAVEIZQ = 20;
  /** RegularExpression Id. */
  int LLAVEDER = 21;
  /** RegularExpression Id. */
  int CORIZQ = 22;
  /** RegularExpression Id. */
  int CORDER = 23;
  /** RegularExpression Id. */
  int PUNTO = 24;
  /** RegularExpression Id. */
  int COMA = 25;
  /** RegularExpression Id. */
  int COMILLAS = 26;
  /** RegularExpression Id. */
  int DOSPUNTOS = 27;
  /** RegularExpression Id. */
  int FINLINEA = 28;
  /** RegularExpression Id. */
  int COMENTARIO = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int SINO = 31;
  /** RegularExpression Id. */
  int ELSIF = 32;
  /** RegularExpression Id. */
  int SWITCH = 33;
  /** RegularExpression Id. */
  int CASE = 34;
  /** RegularExpression Id. */
  int FINCASE = 35;
  /** RegularExpression Id. */
  int MIENTRAS = 36;
  /** RegularExpression Id. */
  int FOR = 37;
  /** RegularExpression Id. */
  int FOREACH = 38;
  /** RegularExpression Id. */
  int REPEAT = 39;
  /** RegularExpression Id. */
  int NUMERO = 40;
  /** RegularExpression Id. */
  int TIPODATO = 41;
  /** RegularExpression Id. */
  int NULO = 42;
  /** RegularExpression Id. */
  int VALOR_BOOLEANO = 43;
  /** RegularExpression Id. */
  int FUNCION = 44;
  /** RegularExpression Id. */
  int CLASE = 45;
  /** RegularExpression Id. */
  int VALOR_OBJETO = 46;
  /** RegularExpression Id. */
  int TIPO_INTERFAZ = 47;
  /** RegularExpression Id. */
  int TIPO_DELEGADO = 48;
  /** RegularExpression Id. */
  int GLOBAL = 49;
  /** RegularExpression Id. */
  int IO = 50;
  /** RegularExpression Id. */
  int RETORNO = 51;
  /** RegularExpression Id. */
  int THEN = 52;
  /** RegularExpression Id. */
  int ITERACION = 53;
  /** RegularExpression Id. */
  int PRUEBA = 54;
  /** RegularExpression Id. */
  int ATRAPADOR = 55;
  /** RegularExpression Id. */
  int COMPARADOR = 56;
  /** RegularExpression Id. */
  int ABRIR_ARCHIVO = 57;
  /** RegularExpression Id. */
  int LEER_ARCHIVO = 58;
  /** RegularExpression Id. */
  int LEER_LINEA = 59;
  /** RegularExpression Id. */
  int MAIN = 60;
  /** RegularExpression Id. */
  int ESCRIBIR = 61;
  /** RegularExpression Id. */
  int ESCRIBIR_LINEA = 62;
  /** RegularExpression Id. */
  int IMPRIMIR = 63;
  /** RegularExpression Id. */
  int EJECUCION = 64;
  /** RegularExpression Id. */
  int ERROR_EXCEPCION = 65;
  /** RegularExpression Id. */
  int ERROR_BLOQUEO = 66;
  /** RegularExpression Id. */
  int ERROR_FINALIZACION = 67;
  /** RegularExpression Id. */
  int SELECTOR = 68;
  /** RegularExpression Id. */
  int METODO_DESDE = 69;
  /** RegularExpression Id. */
  int METODO_TIPO = 70;
  /** RegularExpression Id. */
  int VALOR_DE_OBJETO = 71;
  /** RegularExpression Id. */
  int NUEVO = 72;
  /** RegularExpression Id. */
  int BIBLIOTECA = 73;
  /** RegularExpression Id. */
  int IMPORTAR_BIBLIOTECA = 74;
  /** RegularExpression Id. */
  int ABSTRACCION = 75;
  /** RegularExpression Id. */
  int GET = 76;
  /** RegularExpression Id. */
  int SET = 77;
  /** RegularExpression Id. */
  int THROW = 78;
  /** RegularExpression Id. */
  int PUNTERO = 79;
  /** RegularExpression Id. */
  int MOD_ABSTRAC = 80;
  /** RegularExpression Id. */
  int SUPER = 81;
  /** RegularExpression Id. */
  int PARAMETROS = 82;
  /** RegularExpression Id. */
  int TIPO_METODO = 83;
  /** RegularExpression Id. */
  int ESTATICO = 84;
  /** RegularExpression Id. */
  int VALOR = 85;
  /** RegularExpression Id. */
  int INPUT = 86;
  /** RegularExpression Id. */
  int EVENTO = 87;
  /** RegularExpression Id. */
  int REFERENCIA = 88;
  /** RegularExpression Id. */
  int COMPROBAR = 89;
  /** RegularExpression Id. */
  int DESCOMPROBAR = 90;
  /** RegularExpression Id. */
  int SINCRONIZAR = 91;
  /** RegularExpression Id. */
  int CORRER = 92;
  /** RegularExpression Id. */
  int IGNORAR = 93;
  /** RegularExpression Id. */
  int START = 94;
  /** RegularExpression Id. */
  int REMOVE = 95;
  /** RegularExpression Id. */
  int CLEAR = 96;
  /** RegularExpression Id. */
  int REVERSE = 97;
  /** RegularExpression Id. */
  int COPIAR = 98;
  /** RegularExpression Id. */
  int MAXIMO = 99;
  /** RegularExpression Id. */
  int MINIMO = 100;
  /** RegularExpression Id. */
  int SUMAR = 101;
  /** RegularExpression Id. */
  int DETENER = 102;
  /** RegularExpression Id. */
  int PAUSAR = 103;
  /** RegularExpression Id. */
  int SUSPENDER = 104;
  /** RegularExpression Id. */
  int ADJUNTAR = 105;
  /** RegularExpression Id. */
  int EXTENDER = 106;
  /** RegularExpression Id. */
  int INSERTAR = 107;
  /** RegularExpression Id. */
  int MODMATH = 108;
  /** RegularExpression Id. */
  int HEIGHT = 109;
  /** RegularExpression Id. */
  int WIDTH = 110;
  /** RegularExpression Id. */
  int LEFT = 111;
  /** RegularExpression Id. */
  int RIGHT = 112;
  /** RegularExpression Id. */
  int TOP = 113;
  /** RegularExpression Id. */
  int INDICE = 114;
  /** RegularExpression Id. */
  int METODO = 115;
  /** RegularExpression Id. */
  int TAG = 116;
  /** RegularExpression Id. */
  int BOTTOM = 117;
  /** RegularExpression Id. */
  int CONTAR = 118;
  /** RegularExpression Id. */
  int ORDENAR = 119;
  /** RegularExpression Id. */
  int TIEMPO = 120;
  /** RegularExpression Id. */
  int ALEATORIO = 121;
  /** RegularExpression Id. */
  int CLOSE = 122;
  /** RegularExpression Id. */
  int BUSCAR = 123;
  /** RegularExpression Id. */
  int RENOMBRAR = 124;
  /** RegularExpression Id. */
  int FUNCMAT = 125;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 126;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<OPARITMETICO>",
    "<OPRELACIONAL>",
    "<OPLOGICO>",
    "\"=\"",
    "<OPASIGNACION>",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"?:\"",
    "<APUNTADOR>",
    "\"??\"",
    "\"lambda\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "<COMILLAS>",
    "\":\"",
    "\";\"",
    "\"#\"",
    "\"if\"",
    "\"else\"",
    "\"elsif\"",
    "\"switch\"",
    "\"case\"",
    "\"break\"",
    "\"while\"",
    "\"for\"",
    "\"foreach\"",
    "\"rpt\"",
    "<NUMERO>",
    "<TIPODATO>",
    "\"null\"",
    "<VALOR_BOOLEANO>",
    "\"func\"",
    "\"class\"",
    "\"object\"",
    "\"interface\"",
    "\"del\"",
    "\"global\"",
    "<IO>",
    "\"return\"",
    "\"then\"",
    "\"continue\"",
    "\"try\"",
    "\"catch\"",
    "\"like\"",
    "\"open\"",
    "\"readfile\"",
    "\"readln\"",
    "\"Main\"",
    "\"write\"",
    "\"writeln\"",
    "<IMPRIMIR>",
    "\"exec\"",
    "\"excep\"",
    "\"raise\"",
    "\"finally\"",
    "\"select\"",
    "\"from\"",
    "\"type\"",
    "\"default\"",
    "\"new\"",
    "\"packg\"",
    "\"import\"",
    "\"abstract\"",
    "\"get\"",
    "\"set\"",
    "\"throw\"",
    "\"this\"",
    "\"override\"",
    "\"super\"",
    "\"params\"",
    "<TIPO_METODO>",
    "\"static\"",
    "\"value\"",
    "\"input\"",
    "\"event\"",
    "\"ref\"",
    "\"checked\"",
    "\"unchecked\"",
    "\"sync\"",
    "\"run\"",
    "\"pass\"",
    "\"Start\"",
    "\"Remove\"",
    "\"Clear\"",
    "\"Reverse\"",
    "\"Copy\"",
    "\"Max\"",
    "\"Min\"",
    "\"Sum\"",
    "\"Stop\"",
    "\"Pause\"",
    "\"Sleep\"",
    "\"append\"",
    "\"extend\"",
    "\"insert\"",
    "\"Math\"",
    "\"Height\"",
    "\"Width\"",
    "\"Left\"",
    "\"Right\"",
    "\"Top\"",
    "\"Index\"",
    "\"void\"",
    "\"Tag\"",
    "\"Bottom\"",
    "\"count\"",
    "\"sort\"",
    "\"time\"",
    "\"random\"",
    "\"close\"",
    "\"seek\"",
    "\"rename\"",
    "<FUNCMAT>",
    "<IDENTIFICADOR>",
  };

}
